package servidor.presentacion;

import javax.swing.JButton;

/**
 * Vista donde se renderizaran los elementos necesarios
 */
public class Vista extends javax.swing.JFrame {

    //Cargamos el controlador y modelo de la presentación
    private Controlador controlador;
    private final Modelo modelo;

    /**
     * Inicializamos la vista con los componetes y las acciones
     *
     * @param claseModelo Modelo que se encutra relacionado con la vista
     */
    public Vista(Modelo claseModelo) {
        modelo = claseModelo;
        initComponents();
        AsignarEventos();
    }

    /**
     * Pemite retornar una sola instancia del controlador
     * 
     * @return Controlador retorna el controlador
     */
    public Controlador getControlador() {
        if (controlador == null) {
            controlador = new Controlador(this);
        }
        return controlador;
    }

    /**
     * Obtenemos el modelo relacionado a la vista
     * 
     * @return Retorna el modelo
     */
    public Modelo getModelo() {
        return modelo;
    }

    /**
     * Asignamos los eventos relacionados a la vista
     */
    public void AsignarEventos() {
        btnConectar.addActionListener(getControlador());
    }

    /**
     * Retornamos la instancia de la clase button
     * 
     * @return Retornamos la instancia del boton crear semaforos
     */
    public JButton getBtnConectar() {
        return btnConectar;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnConectar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("framePrincipal"); // NOI18N

        btnConectar.setText("Conectar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(btnConectar)
                .addContainerGap(283, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(btnConectar)
                .addContainerGap(186, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("framePrincipal");
        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConectar;
    // End of variables declaration//GEN-END:variables
}
